apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: teleport-kube-agent
  namespace: teleport-kube-agent
spec:
  interval: 10m
  chart:
    spec:
      chart: teleport-kube-agent
      version: 16.5.12
      sourceRef:
        kind: HelmRepository
        name: teleport-kube-agent
        namespace: teleport-kube-agent
  values:
    proxyAddr: teleport.kubelize.com:443
    roles: "kube,app,discovery"
    kubernetesDiscovery:
      - types: ["app"]
        namespaces: ["*"]
        labels:
          "teleport.dev/enabled": "true"
      - types: ["app"]
        namespaces: ["*"]
        labels:
          "teleport.dev/enabled": "on"
    joinTokenSecret:
      create: false
    podSecurityPolicy:
      enabled: false
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 265Mi
    initSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - all
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      runAsUser: 9807
      seccompProfile:
        type: RuntimeDefault
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - all
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      runAsUser: 9807
      seccompProfile:
        type: RuntimeDefault
    highAvailability:
      replicaCount: 2
      requireAntiAffinity: true