apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: no-ghoritch-page
  namespace: growth-vat
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
