apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: patch
  namespace: argocd
spec:
  project: default
  source:
    chart: vcluster
    repoURL: https://charts.loft.sh
    targetRevision: *
    helm:
      releaseName: my-vcluster  
  destination:
    server: https://kubernetes.default.svc
    namespace: a02-reserved