apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: vault
  source:
    repoURL: https://helm.releases.hashicorp.com
    chart: vault
    targetRevision: 0.28.0
    helm:
      releaseName: vault
      valuesObject:
        server:
          ha:
            enabled: false
          dev:
            enabled: true
        ui:
          enabled: true
        injector:
          enabled: false
