apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vault-ca
  namespace: vault-{{ .environment.stage }}
spec:
  isCA: true
  commonName: vault-ca
  secretName: vault-ca
  duration: 8760h
  renewBefore: 720h
  issuerRef:
    name: vault-selfsigned
    kind: Issuer
