apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - app.yaml
patches:
  - target:
      kind: Application
      name: vault
    path: ../../../../common/patches/argocd-app-settings.yaml