apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vault-server-tls
  namespace: vault
spec:
  secretName: vault-server-tls
  duration: 2160h
  renewBefore: 360h
  issuerRef:
    name: vault-ca
    kind: Issuer
  commonName: vault
  dnsNames:
    - vault
    - vault.vault
    - vault.vault.svc
    - vault.vault.svc.cluster.local
    - vault-active
    - vault-active.vault
    - vault-active.vault.svc
    - vault-active.vault.svc.cluster.local
    - vault-standby
    - vault-standby.vault
    - vault-standby.vault.svc
    - vault-standby.vault.svc.cluster.local
