apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "metrics-server"
  namespace: argocd
  labels:
    name: "metrics-server"
spec:
  destination:
    # Must Run in Kube-System
    namespace: kube-system
  source:
    repoURL: https://kubernetes-sigs.github.io/metrics-server/
    targetRevision: 3.12.2
    chart: metrics-server
    helm:
      valuesObject:
        replicas: 2
        podDisruptionBudget:
          enabled: true
          minAvailable: 1
