apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:

# Connectivity
  - ../../../operators/connectivity/cilium/
  - ../../../operators/connectivity/cert-manager/
  - ../../../operators/connectivity/ingress-nginx/

# GitOps
  - ../../../operators/gitops/argocd/

# Security
  - ../../../operators/security/kyverno/
  - ../../../operators/security/teleport-kube-agent/

# Storage
  - ../../../operators/storage/csi-proxmox/
  - ../../../addons/storageclasses/csi-proxmox/