apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - app.yaml
  - namespace.yaml
patches:
  - target:
      kind: Application
      name: csi-proxmox
    path: ../../../patches/argocd-app-settings.yaml