---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tf-runner
  namespace: vault-{{ .environment.stage }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tf-runner
  namespace: vault-{{ .environment.stage }}
rules:
  # Permissions to manage secrets for outputs and tfplan
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  # Permissions to read configmaps
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch"]
  # Permissions for Terraform state locking
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tf-runner
  namespace: vault-{{ .environment.stage }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tf-runner
subjects:
  - kind: ServiceAccount
    name: tf-runner
    namespace: vault-{{ .environment.stage }}
