apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: csi-snapshot-controller
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  sources:
    - repoURL: https://github.com/kubelize/platform
      targetRevision: main
      path: apps/operators/storage/csi-snapshot-controller/deploy
