apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  sources:
    - repoURL: https://charts.jetstack.io
      targetRevision: v1.19.3
      chart: cert-manager
      helm:
        parameters: []
        valuesObject:
          crds:
            enabled: true
          ingressShim:
            defaultIssuerName: letsencrypt-prod-nginx
            defaultIssuerKind: ClusterIssuer
    - repoURL: https://github.com/kubelize/platform
      targetRevision: prod
      path: apps/operators/connectivity/cert-manager/addons
    
