apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - app.yaml
  - providers-app.yaml
patches:
  - target:
      kind: Application
      name: crossplane
    path: ../../../../common/patches/argocd-app-settings.yaml
  - target:
      kind: Application
      name: crossplane-providers
    path: ../../../../common/patches/argocd-app-settings.yaml