---
# Example patch for configuring Velero with AWS S3
# Apply this in your cluster's patches directory

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: velero
  namespace: argocd
spec:
  sources:
    - repoURL: https://vmware-tanzu.github.io/helm-charts
      targetRevision: 7.2.1
      chart: velero
      helm:
        valuesObject:
          configuration:
            backupStorageLocation:
              - name: default
                provider: aws
                bucket: my-velero-backups  # Update with your bucket name
                config:
                  region: us-west-2  # Update with your region
          
          # If using IRSA (IAM Roles for Service Accounts)
          serviceAccount:
            server:
              annotations:
                eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNT_ID:role/VeleroRole
