apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "crossplane-providers"
  namespace: "argocd"
spec:
  project: default
  destination:
    namespace: "crossplane-system"
    server: "https://kubernetes.default.svc"
  source:
    repoURL: https://bedag.github.io/helm-charts
    targetRevision: 2.0.0
    chart: raw
    helm:
      valuesObject:
        resources:
          ##### DeploymentRuntimeConfigs #####
          - apiVersion: pkg.crossplane.io/v1
            kind: DeploymentRuntimeConfig
            metadata:
              name: default
            spec:
              deploymentTemplate:
                spec:
                  selector: {} # apply to all providers
                  template:
                    spec:
                      securityContext:
                        runAsNonRoot: true
                        runAsUser: 65534
                        fsGroup: 65534
                        seccompProfile:
                          type: RuntimeDefault
                      containers:
                        - name: package-runtime
                          securityContext:
                            allowPrivilegeEscalation: false
                            runAsNonRoot: true
                            runAsUser: 65534
                            capabilities:
                              drop:
                                - ALL
          - apiVersion: pkg.crossplane.io/v1
            kind: DeploymentRuntimeConfig
            metadata:
              name: provider-kubernetes
            spec:
              serviceAccountTemplate:
                metadata:
                  name: provider-kubernetes
              deploymentTemplate:
                spec:
                  selector: {} # apply to all providers
                  template:
                    spec:
                      securityContext:
                        runAsNonRoot: true
                        runAsUser: 65534
                        fsGroup: 65534
                        seccompProfile:
                          type: RuntimeDefault
                      containers:
                        - name: package-runtime
                          securityContext:
                            allowPrivilegeEscalation: false
                            runAsNonRoot: true
                            runAsUser: 65534
                            capabilities:
                              drop:
                                - ALL
          - apiVersion: pkg.crossplane.io/v1
            kind: Provider
            metadata:
              name: provider-kubernetes
            spec:
              package: xpkg.upbound.io/crossplane-contrib/provider-kubernetes:v1.2.0
              runtimeConfigRef:
                name: provider-kubernetes
          - apiVersion: pkg.crossplane.io/v1
            kind: Provider
            metadata:
              name: provider-helm
            spec:
              package: xpkg.upbound.io/crossplane-contrib/provider-helm:v1.1.0
              runtimeConfigRef:
                name: default
          # - apiVersion: pkg.crossplane.io/v1
          #   kind: Provider
          #   metadata:
          #     name: provider-vault
          #   spec:
          #     package: xpkg.upbound.io/upbound/provider-vault:v2.2.1
          #     runtimeConfigRef:
          #       name: default
          ##### Functions #####
          - apiVersion: pkg.crossplane.io/v1
            kind: Function
            metadata:
              name: function-go-templating
            spec:
              package: xpkg.upbound.io/crossplane-contrib/function-go-templating:v0.11.3
              runtimeConfigRef:
                name: default
          - apiVersion: pkg.crossplane.io/v1
            kind: Function
            metadata:
              name: function-auto-ready
            spec:
              package: xpkg.upbound.io/crossplane-contrib/function-auto-ready:v0.6.0
              runtimeConfigRef:
                name: default
          - apiVersion: pkg.crossplane.io/v1
            kind: Function
            metadata:
              name: function-patch-and-transform
            spec:
              package: xpkg.upbound.io/crossplane-contrib/function-patch-and-transform:v0.10.0
              runtimeConfigRef:
                name: default
