apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: velero
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: velero
  sources:
    - repoURL: https://vmware-tanzu.github.io/helm-charts
      targetRevision: 11.3.2
      chart: velero
      helm:
        valuesObject:
          # Initialize the server with the default configuration
          initContainers:
            - name: velero-plugin-for-aws
              image: velero/velero-plugin-for-aws:v1.10.1
              volumeMounts:
                - mountPath: /target
                  name: plugins

          configuration:
            # Note: Proxmox CSI driver doesn't support CSI snapshots yet
            # Using file-level backups with kopia instead
            # features: EnableCSI
            
            backupStorageLocation:
              - name: default
                provider: aws
                bucket: velero
                config:
                  region: minio
                  s3ForcePathStyle: "true"
                  s3Url: "http://s3-kaji:9000"
            
            # Disable volume snapshot location (not using snapshots)
            volumeSnapshotLocation: []
            
            # Use file-level backups (kopia) for PVs
            defaultVolumesToFsBackup: true
          
          # Deploy node-agent DaemonSet for file-level backups
          deployNodeAgent: true
          
          # Node-agent configuration
          nodeAgent:
            podVolumePath: /var/lib/kubelet/pods
            privileged: false
            resources:
              requests:
                cpu: 500m
                memory: 512Mi
              limits:
                cpu: 1000m
                memory: 1Gi
            tolerations: []

          # Credentials for S3 access (will be patched per-cluster)
          credentials:
            useSecret: true
            existingSecret: velero-credentials

          # Resource requests/limits
          resources:
            requests:
              cpu: 500m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 1Gi

          # Backup/restore settings
          schedules: {}  # Define schedules in separate files
          
          # Node selector (optional, can be patched per cluster)
          nodeSelector: {}
          
          # Tolerations (optional)
          tolerations: []
          
          # Service account annotations (for IRSA if using AWS)
          serviceAccount:
            server:
              create: true
              name: velero
              annotations: {}
          kubectl:
            image:
              repository: docker.io/bitnamilegacy/kubectl
              tag: latest