apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: patch
spec:
  project: default
  sources:
    - repoURL: https://github.com/kubelize/tenants
      path: clusters/home-dhe
      targetRevision: main