apiVersion: v1
kind: Secret
metadata:
    name: etcd-certs
    namespace: observability-system
type: Opaque
stringData:
    etcd-ca.crt: ENC[AES256_GCM,data:as6nlixkhtbt2U8TPNVhTXR2X33ILafuV0dSij6bk4DMQHLeAfuMarcZFuEtX9IyYroL1MWHYnx5SFAOb3TcPwrClowHM/5d4aU2iLEJnCphdadJwMbXm20m4N1YuxLj5fh/gOJJhb7udniRlfj1gw3dgeICH2YvA96Br9iuUfGZtN/d2J17nFKfVIcObWnhyDldb0OzVJ25mg/BRKFTgK0GEfMfwVHXvaJbp8Dg0jLrNQVO8J1Fi32x8gD8aa1wFEdOdISl/K+0M2F2evFZOfkujPlxjNNhP+CP+XDeDQzqdp4r4fH+LQyg/9ondoBWZP3MM7Dtp+h4387iX/OgyzsAak56ELFPsrvLCZWzvSXodMCs9hsld1hGPMJR9Fotk/c11PqRs771/t/GEeKFZQ3Z6sA/mo8/T5TPnQDoZo5edeViHEaDvHNSdeTIiz56Pcyi0Nmj/JQs+myibctciiB9NN6ISzORwO/DD1uJ8XaIcydqd5z8oTaQOc9l50uAIE+ZhGNuUyb8WuX1uD2qK2uFusfzQlEjmq7W8S4G2mZQGbIVNxzPFvQZkp+3T1W1gZ/4JloJyhA+uIRIrB/Z9vq44o/wAJ3UZN6HBI5wQ42w/6ZJZ2HkU7auRtvqAX1QkJvtF7WTyM8Glo9KZqfONNJehzRpNmPrcJtaBBOfFj8VP3PF5EBgGEMJVxCYTs1ypJWobqaVCqesFsOkb/xaqBxxVAICW9o6bf1dSbphS7qCzXiEu94ALUA6jJAw+V9gGu9j,iv:jE0cMMfi8UYWjb5o3QUrjUehcUWvf6qBDkRP1zq+Mxs=,tag:J+cvYdIMMS1x5NZsTO694g==,type:str]
    etcd-client.crt: ENC[AES256_GCM,data:3YUZ8hkyFskiIjuXLW+gO2pKp568LQbCfP5Abj9VGhPxcFiuOd2wM4iYxVoJoJCRZ6g12LAH3UmH5c5xA0UL5jRkmI/FVRC20aKJJsJM6rupb88VOkc2GZtHffuid1kteWeZjKaWLbBBhOtkeiYS7lLO8ddya2mrwKrkyVMqNF9c6EEt53ODCPMPY0QqxNYBhQay/ANIo7FeW1iDb1DRHgIw6wPnZc2XCbVR18tJHm+xHt/O/SuCOpiDIIpSaQvCLegKRqatXgcZGjfHx53NpDtCllVsEBSaV8zk1bc9mmL24YHsSj5UNBeRVgF6jb9rb/THnmq7xxeLy+YwBlglnmXl4rUqRglWbLUjKrDHKmnUc2M0fbl5n7gNv1mQXFvX3BehuNXzmQSlpeY+qWXEYikTID3j7tpIdFpjcwhZX0YCNrw4/OrVn2EsIxnRv1Ax5Ln0TTLs9ENQeEwWtCm4DsmTJSkivRTCEJXOyByi5YlrMCMMMOs3rCX3pu7SCK8IkmHpp5dicef4IWD+IrfUKb9l5wPvTwuqvS84zJ5ZhKi+mG8b4Spt0EhuMUTEjJ5ugg06mGE/n2ElZcW++/AfzdigeX9pTAdcVksPqrWiHZ8WGGy3iIWlfgkSnLXv2YT/rqIVpYk7UcAp9mpJTUr9/ptutw7hFTi15JW6Ud2EuMsaYoZVvcnE9F4eBwaiulEgusmJHRaLQnmfKAZ9g8uBAkahw+kQUk1rEfzA8zM57ggaX6JI1zRtvm5z/NQ+YReUp2r/tDNnYfaLZYE6WumPrYEPRkFyEa3ecLq2rRty4lAcZgY4xNXo1sTXsp5OpIGeRKn6mfPHuk9MGaQAbB3Jx1R9YQII+2/TDPrvaw==,iv:zYBRvhlaMOlNm0tDztRlQOgMF4czphGQY+PlPxx9svk=,tag:XjZAKwvLfBLhAbjlPz93cw==,type:str]
    etcd-client-key.key: ENC[AES256_GCM,data:cIzTglui6w7Nbfk5bruuz4kDwSrahXTSYhF/Nkp8La6NQbcBcRIi/BOT+t2h8Y22e2hSrHmKhFsGizqO9LKEfJyZiHUPeD2prZZMbqEJ2bg1MEHqkURZagfx9IFnpO2gcIWLUWwJX0HFZAIq8qw3D7LBYYoyflEPFqBgcVaLq+TELSkS5dxH3HjTbadkLOuz7gQ87j/EHNVx56iFbZ9LsucxqsC6qdelRy4XHJj8MPPdO2VOVcgr19OikXvApNHqsVgRqlIeUwi+nwBtsigZAGVR2duC3zhdFWHpC6f+WnA9uHo=,iv:4tDFOyckTHie07zP8pBj8MO6UKCgMAVZ2MB2A7xEIls=,tag:qRdoztHZ84FaZvRVewQeuA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-09-22T18:25:50Z"
    mac: ENC[AES256_GCM,data:g01uFZLT6MXd8RX0WCRvCQMy+0qyT/CovC1BX1GtwUAIRg2EWWFXngveUcO71mu3mSvUs8nO0xyFemldIwifd8uanmIUkrPDgv4Q4b/u2O3YBzvpBOBjUAZ4fvk3yGk8vLCE/6a6GEMIa0zdbP1UvdWi2j3fM3WyzDFqX40u3ag=,iv:xlgKouia/A2mVP3Me8NNhFeiARI5rgXyTX7inPPk3Sw=,tag:7I28edNZrINdPoOuYMNuDg==,type:str]
    pgp:
        - created_at: "2025-09-22T18:25:50Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwFcjQZ1ckKcARAAxv8Nr618ZAyPQITBcoV35gWWk2vTtUh0YdJPgrsaYO1r
            GwEBV0E6AjL6P1hgKeQP7wXTv9sRlswTOTZW+S+TEpf0L+f6W0KfT9Nn48az1rM9
            vpN1zXPs569/reGX7SY3NRy2ku32U7hGkLoCJ/71kH+clPSFesSqgYFbSHSjC/cC
            gC4Vyyh77yY9LBKF6raO4ac7oVYXrIOTxE2zAPBqj4WieyxvzGYsrpbFjp0evZv3
            E081cpC/6JzVdB7NgxqTI8UAZYP/Z4AgG5ThDXV9BomBNwD++7qMbMX8UDxFeOge
            yl1UNGUPApvEwyQPe3PcsfNc6O6Rs9RK20YnHIWIMc2gxoPJ/qqWLUEO7GdbaWxl
            a5fy5m3V8vPfu0dQZcQqRRB8XnNiBUfFhq0VfQVQew+L9WNYbd1Wen52/cDUHEqR
            f2MEcNBY3d7K/AgRxIT8G+Hlb52Ppw8KHbuRyRku3BfHSIR55UAAD1La85NLy2D5
            ns3Ngl7hUlhxoKo6Rb53ZgcrMiKFGhB9A5iKWaNL1uRNovCtNydUb7gyhFC21dCA
            uoU12LBdxhO1jJlq9/rQSbJhG+z0IPH+hrfduPjpww5x+Qu/0TGPI3a8Xrl+U7m8
            rj/CQrMsLTOYgY6nhzSexWUjCKc7s+pPPoI7lAuZfM/LdYa+w5ElNqUyjigYxsDU
            aAEJAhDXM252t1ol/3LT1Xiaro6TsfwhXxXnwLzEQr/YDkDq4B/nbfWUpWbmiTT2
            6dyg5+KjJRV2bzboiG1YluNmlCaxz66r4ARBpb2TrVLAX7RSkPAQBGjYpiAcuqjU
            /ttWPi+1FnRQ
            =qmCr
            -----END PGP MESSAGE-----
          fp: 4C460A5D1A91A52F3E204754CA746D9D4345890B
    encrypted_regex: ^(data|stringData|secrets)$
    version: 3.9.4
