apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: kube-system
spec:
  containers:
  - image: busybox
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: busybox
    volumeMounts:
    - mountPath: /system/secrets/etcd
      name: k8setcdcert
  hostNetwork: true
  nodeSelector:
    kubernetes.io/hostname: service-120425-01
  tolerations:
    - key: node-role.kubernetes.io/control-plane
      operator: Exists
      effect: NoSchedule
    - key: node-role.kubernetes.io/master
      operator: Exists
      effect: NoSchedule
  volumes:
  - hostPath:
      path: /system/secrets/etcd
      type: ""
    name: k8setcdcert
  hostNetwork: true
  restartPolicy: Always