apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: projects
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/kubelize/projects
      path: environments/clusters/home-dhe
      targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd