apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno-policies
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: kyverno-system
  source:
    repoURL: https://kyverno.github.io/kyverno/
    targetRevision: 3.4.1
    chart: kyverno-policies
    helm:
      parameters: []
      valuesObject:
        podSecurityStandard: baseline
        validationFailureAction: Audit
        validationFailureActionOverrides:
          all:
          - action: Audit
            namespaces:
            - "*system*"
          # - action: Enforce
          #   namespaceSelector:
          #     matchLabels:
          #       kyverno-policies-mode: enforce
