---
# Example patch for configuring Velero with MinIO
# Apply this in your cluster's patches directory

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: velero
  namespace: argocd
spec:
  sources:
    - repoURL: https://vmware-tanzu.github.io/helm-charts
      targetRevision: 7.2.1
      chart: velero
      helm:
        valuesObject:
          configuration:
            backupStorageLocation:
              - name: default
                provider: aws
                bucket: velero-backups
                config:
                  region: us-east-1
                  s3ForcePathStyle: "true"
                  s3Url: "http://minio.storage.svc.cluster.local:9000"  # Update with your MinIO endpoint
