apiVersion: v1
kind: Secret
metadata:
  name: proxmox-credentials
  namespace: crossplane-system
type: Opaque
stringData:
  credentials: |
    {
      "api_url": "{{ .ejson.fabric.apiUrl }}",
      "api_token": "{{ .ejson.fabric.proxmoxToken }}"
    } 