apiVersion: v1
kind: Secret
metadata:
  name: proxmox-terraform-creds
  namespace: crossplane-system
type: Opaque
stringData:
  api_url: "{{ .ejson.fabric.apiUrl }}"
  token_id: "{{ .ejson.fabric.tokenId }}"
  token_secret: "{{ .ejson.fabric.tokenSecret }}"