apiVersion: v1
kind: Secret
metadata:
  name: proxmox-credentials
  namespace: crossplane-system
type: Opaque
stringData:
  credentials: |
    {
      "endpoint": "{{ .ejson.fabric.apiUrl }}",
      "api_token": "{{ .ejson.fabric.proxmoxToken }}",
      "insecure": "true"
    } 