apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: csi-driver-nfs
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: nfs-system
  sources:
    - repoURL: https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts
      targetRevision: 4.13.1
      chart: csi-driver-nfs
      helm:
        valuesObject:
          controller:
            replicas: 2
          feature:
            enableFSGroupPolicy: true
          kubeletDir: /var/lib/kubelet
