apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: argocd
  namespace: argocd
spec:
  interval: 10m
  chart:
    spec:
      chart: argo-cd
      version: 8.1.1
      sourceRef:
        kind: HelmRepository
        name: argocd
        namespace: argocd
  values:
    crds:
      enabled: true
    configs:
      params:
        server.insecure: true
        server.disable.auth: true
      cm:
        kustomize.buildOptions: --load-restrictor LoadRestrictionsNone
