apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: argocd
  namespace: argocd
spec:
  interval: 10m
  chart:
    spec:
      chart: argo-cd
      version: 8.1.1
      sourceRef:
        kind: HelmRepository
        name: argocd
        namespace: argocd
  values:
    crds:
      enabled: true
    configs:
      params:
        server.insecure: true
        server.disable.auth: true
      cm:
        kustomize.buildOptions: --load-restrictor LoadRestrictionsNone
        resource.exclusions: |
          ### Network resources created by the Kubernetes control plane and excluded to reduce the number of watched events and UI clutter
          - apiGroups:
            - ''
            - discovery.k8s.io
            kinds:
            # - Endpoints
            - EndpointSlice
          ### Internal Kubernetes resources excluded reduce the number of watched events
          - apiGroups:
            - coordination.k8s.io
            kinds:
            - Lease
          ### Internal Kubernetes Authz/Authn resources excluded reduce the number of watched events
          - apiGroups:
            - authentication.k8s.io
            - authorization.k8s.io
            kinds:
            - SelfSubjectReview
            - TokenReview
            - LocalSubjectAccessReview
            - SelfSubjectAccessReview
            - SelfSubjectRulesReview
            - SubjectAccessReview
          ### Intermediate Certificate Request excluded reduce the number of watched events
          - apiGroups:
            - certificates.k8s.io
            kinds:
            - CertificateSigningRequest
          - apiGroups:
            - cert-manager.io
            kinds:
            - CertificateRequest
          ### Cilium internal resources excluded reduce the number of watched events and UI Clutter
          - apiGroups:
            - cilium.io
            kinds:
            - CiliumIdentity
            - CiliumEndpoint
            - CiliumEndpointSlice
          ### Kyverno intermediate and reporting resources excluded reduce the number of watched events and improve performance
          - apiGroups:
            - kyverno.io
            - reports.kyverno.io
            - wgpolicyk8s.io
            kinds:
            - PolicyReport
            - ClusterPolicyReport
            - EphemeralReport
            - ClusterEphemeralReport
            - AdmissionReport
            - ClusterAdmissionReport
            - BackgroundScanReport
            - ClusterBackgroundScanReport
            - UpdateRequest
    global:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
    controller:
        containerSecurityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - all
          readOnlyRootFilesystem: true
          runAsUser: 1001
          runAsGroup: 1001
    server:
      containerSecurityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - all
        readOnlyRootFilesystem: true
        runAsUser: 1001
        runAsGroup: 1001
    dex:
      enabled: false
      containerSecurityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - all
        readOnlyRootFilesystem: true
        runAsUser: 1001
        runAsGroup: 1001
    applicationSet:
      containerSecurityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - all
        readOnlyRootFilesystem: true
        runAsUser: 1001
        runAsGroup: 1001
      allowAnyNamespace: true
    notifications:
      enabled: false
    repoServer:
      containerSecurityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - all
        readOnlyRootFilesystem: true
        runAsUser: 1001
        runAsGroup: 1001
      volumes:
        - emptyDir: {}
          name: custom-tools
        - emptyDir: {}
          name: subst-tmp
        - emptyDir: {}
          name: subst-kubeconfig
        - name: subst-cmp-plugin
          configMap:
            name: argocd-subst-cmp
            items:
              - key: plugin.yaml
                path: plugin.yaml
      extraContainers:
        - name: cmp-subst
          args:
            - /var/run/argocd/argocd-cmp-server
            - --loglevel
            - info
          image: kubelize/subst-cmp:v1.0.6
          imagePullPolicy: Always
          env:
            # has to be equal or greater than 'server.repo.server.timeout.seconds' & 'controller.repo.server.timeout.seconds'
            - name: ARGOCD_EXEC_TIMEOUT
              value: "5m30s"
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - all
            readOnlyRootFilesystem: true
            runAsUser: 1001
            runAsGroup: 1001
          resources:
            limits:
              cpu: 6000m
              memory: 4096Mi
            requests:
              cpu: 1500m
              memory: 128Mi
          volumeMounts:
            - mountPath: /var/run/argocd
              name: var-files
            - mountPath: /home/argocd/cmp-server/plugins
              name: plugins
            # Starting with v2.4, do NOT mount the same tmp volume as the repo-server container. The filesystem separation helps
            # mitigate path traversal attacks.
            - mountPath: /tmp
              name: subst-tmp
            - mountPath: /etc/kubernetes/
              name: subst-kubeconfig
            - mountPath: /home/argocd/cmp-server/config/plugin.yaml
              subPath: plugin.yaml
              name: subst-cmp-plugin

