apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: argocd
  namespace: argocd
spec:
  interval: 10m
  chart:
    spec:
      chart: argo-cd
      version: 8.1.1
      sourceRef:
        kind: HelmRepository
        name: argocd
        namespace: argocd
  values:
    crds:
      enabled: true
    configs:
      params:
        server.insecure: true
        server.disable.auth: true
      cm:
        kustomize.buildOptions: --load-restrictor LoadRestrictionsNone
        
    # Add gomplate CMP to the repo server
    repoServer:
      extraContainers:
        - name: gomplate-cmp
          image: kubelize/gomplate-cmp:latest
          securityContext:
            runAsNonRoot: true
            runAsUser: 999
            runAsGroup: 999
          volumeMounts:
            - name: var-files
              mountPath: /var/run/argocd
            - name: plugins
              mountPath: /home/argocd/cmp-server/plugins
            - name: gomplate-cmp-tmp
              mountPath: /tmp
          env:
            - name: ARGOCD_EXEC_TIMEOUT
              value: "90s"
      
      volumes:
        - name: gomplate-cmp-tmp
          emptyDir: {}